### ISSUE TITLE
You can drop duplicate edges by setting the 'duplicates' kwarg

### ISSUE THREAD

**Issue by willbelucky** [willbelucky/ksif#2]
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-3-20567499fdd1>", line 6, in <module>
>     show_plot=True
>   File "/Users/willbe/PycharmProjects/ksif/ksif/core/frame.py", line 172, in quantile_distribution_ratio
>     lambda x: pd.qcut(x, chunk_num, labels=labels)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/groupby.py", line 3287, in transform
>     res = wrapper(group)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/groupby.py", line 3284, in <lambda>
>     wrapper = lambda x: func(x, *args, **kwargs)
>   File "/Users/willbe/PycharmProjects/ksif/ksif/core/frame.py", line 172, in <lambda>
>     lambda x: pd.qcut(x, chunk_num, labels=labels)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/tile.py", line 208, in qcut
>     dtype=dtype, duplicates=duplicates)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/tile.py", line 234, in _bins_to_cuts
>     "the 'duplicates' kwarg".format(bins=bins))
> ValueError: Bin edges must be unique: array([ 7.82673683,  7.82673683,  7.82673683,  7.82673683,  7.82673683,
>         7.82673683,  7.82673683,  7.82673683,  7.82673683,  7.82673683,
>         7.82673683]).
> You can drop duplicate edges by setting the 'duplicates' kwarg

**Comment by willbelucky** [comment]
## Trial 1
- 원인: 원본 데이터에 ret1 column에 대부분이 nan으로 들어가있음.
- 해결책: ksif_preprocessing에서 본 문제 해결
